{% set version = "0.4.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-networkd3
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/networkD3_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/networkD3/networkD3_{{ version }}.tar.gz
  sha256: 5be36aa5dd3722b1cd52a149c50af2dbef0714b2dab2b4dbf7552c628925f64e

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-data.tree
    - r-htmlwidgets >=0.3.2
    - r-igraph
    - r-jsonlite
    - r-magrittr
  run:
    - r-base
    - r-data.tree
    - r-htmlwidgets >=0.3.2
    - r-igraph
    - r-jsonlite
    - r-magrittr

test:
  commands:
    - $R -e "library('networkD3')"           # [not win]
    - "\"%R%\" -e \"library('networkD3')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=networkD3
  license: GPL-3.0-or-later
  summary: Creates 'D3' 'JavaScript' network, tree, dendrogram, and Sankey graphs from 'R'.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
