# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "OS4nQiStA4C/NVEhwc/PKHoU53tuQIZ/qsZ5aVJ3oky/PGqRg1Twq1EbHdJJYLr9M2aQJUxcDspU5LDat5wpd8J4lVGCmKbaL+Z7/z5G6l6JdLvql0qyR3Luu7IWZz9tLJZQn9E3gCLYL+iXTVcChGQePfMpPajr97UYnZ9cO6c1AZOPtmZTEu17hV/cwQx8gG+VBHJYlN4oHT4OY+Z2I/sqBvNZFQSTR9qI4WUzbkkkDUWOxXxX/v8fvVE16zv/U2sTt8RZX61iTPhNW8VQzsJWyKvUzEWxsO23+PCissnxMRs3+gViHuqzgO6qo6gptvyXMPN1NGSnynEu8G2vMbg5OUn0i6qBr/Qj5zZSoZPw3+62lzqF/wnW30IqgdzdLS1gLyhaU1p72ys56JohVI6QIQwKDkyKi9/dyQ3rB+Bk8Zv9Q6axuOYmfDj2179YfVm9F/lf1dMotyJmGgVh89zNKP1VKGIek2rhMcq3BEhe77mx7ci+wSlG2P/aJ5NbdKxFA3RR3VuXZ+SOpDhI8b456WZLFdLYqVPXDhxgGtTvS3T5UblpUuZ3KrJSEzlwYImKxPXqEW9eQy+OY569s0CxHUIW85KMk0QjhWA3WhJB1CprJlNURhDXxwAep84gTAEGhdKMpy+nx7mBb73ja7iHfTn06TXqhOlDb7DYO3Y="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
